method: ein_seld
dataset: l3das22 # l3das21 | l3das22
workspace_dir: ./
dataset_dir: /mnt/hjb/Dataset/L3DAS22/dataset 
hdf5_dir: ./_hdf5
task: seld # seld 
data:
  num_foa: 2 # 1 | 2
  label_normalize: respective # respective | unified | 
  train_chunklen_sec: 5
  train_hoplen_sec: 5
  test_chunklen_sec: 5
  test_hoplen_sec: 5
  audio_feature: SALSA # SALSA | logmel&intensity 
  logmelIV: 
    sample_rate: 32000
    n_fft: 1024
    hop_length: 400
    n_mels: 128
    window: hann
    fmin: 20
    fmax: 16000
    feature_freeze: True
  SALSA:
    sample_rate: 32000
    n_fft: 512
    win_length: 512
    hop_length: 400  
    fmin: 50
    fmax: 16000  
    cond_num: 5
training:
  train_id: SALSA_ConvConformer_n1
  model: ConvConformer # ConvConformer | DenseConformer
  resume_model: #None_epoch_latest.pth
  loss_type: all
  loss_beta: 0.85
  PIT_type: tPIT
  batch_size: 32
  overlap: 1&2&3
  optimizer: adamw
  lr: 0.0003
  lr_step_size: 70
  lr_gamma: 0.1
  max_epoch: 100
  train_set: train # train | train&dev
  valid_set: dev
  threshold_sed: 0.5
  remark: None
inference:
  infer_id: Dev_SALSA_ConvConformer_n1
  testset_type: dev # dev | test | train
  overlap: 1&2&3
  train_ids: SALSA_ConvConformer_n1
  models: ConvConformer
  batch_size: 8
  threshold_sed: 0.5
  model_mark: latest
  remark: None


